# yamllint disable rule:quoted-strings
name: Bug report
description: Report a bug or regression
title: [Bug]
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill in the details below.
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Commit SHA, tag, or release version
      placeholder: e.g. 6f3c2c1 or v0.1.0
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS and Node.js version
      placeholder: macOS 14.3, Node 24.13.0
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear, ordered steps.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Redact any sensitive data.
